logging.level.root=INFO
logging.level.com.uniquindio=DEBUG

JWT.SECRET.KEY=${JWT_SECRET_KEY}
JWT.TIME.EXPIRATION=${JWT_TIME_EXPIRATION}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Static resources
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

# Mail configuration
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Payment configuration
stayhub.payment.bank-account=${PAYMENT_BANK_ACCOUNT}
stayhub.payment.deposit-percentage=20
stayhub.payment.deadline-days=3

management.endpoints.web.exposure.include=*