package edu.uniquindio.stayhub_v2.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Entity representing a seasonal pricing rule associated with an {@link Accommodation}.
 *
 * <p>A rental package lets a host define a custom nightly price for a specific
 * date range. When a package is active for a given period its
 * {@code pricePerNight} <b>replaces</b> the accommodation's base
 * {@code pricePerNight}.</p>
 *
 * <p><b>Overlap rule:</b> No two packages belonging to the same accommodation may
 * have overlapping date ranges, regardless of their type. This is enforced at the
 * service layer before persistence.</p>
 *
 * <p><b>Relationships:</b></p>
 * <ul>
 *   <li><b>Accommodation:</b> Many-to-One — many packages can belong to one accommodation.</li>
 * </ul>
 *
 * @author StayHub Dev Team
 * @version 1.0
 * @since 1.0
 * @see Accommodation
 */
@Entity
@Table(
        name = "rental_packages",
        indexes = {
                @Index(name = "idx_rental_package_accommodation", columnList = "accommodation_id"),
                @Index(name = "idx_rental_package_dates", columnList = "start_date, end_date")
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@SuperBuilder
public class RentalPackage extends Auditable {

    /**
     * Unique identifier generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The accommodation this package belongs to.
     *
     * <p>Required. Each package must be tied to exactly one accommodation,
     * and only the host owner of that accommodation may create or modify
     * its packages.</p>
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "accommodation_id", nullable = false)
    private Accommodation accommodation;

    /**
     * First day (inclusive) the package is active.
     *
     * <p>Must be today or a future date. Must be strictly before {@link #endDate}.</p>
     */
    @Column(name = "start_date", nullable = false)
    private LocalDate startDate;

    /**
     * Last day (inclusive) the package is active.
     *
     * <p>Must be strictly after {@link #startDate}.</p>
     */
    @Column(name = "end_date", nullable = false)
    private LocalDate endDate;

    /**
     * Nightly price charged during this package period.
     *
     * <p>Replaces the accommodation's base {@code pricePerNight} for any
     * reservation that falls within the package date range.</p>
     */
    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal pricePerNight;
}
